### ISSUE TITLE
Hi richard sorry this is the wrong rep but I’m using yr homebridge vantage which doesn’t have issues

### ISSUE THREAD

**Issue by stevefnz** [richardpack/homebridge-multizone-amp#1]
And trying to get in contact to see if you could advise , I have it running and I see the read xml etc but it never allows homebridge to start always seems in a start loop , I do have a very large vantage system and I looked in the code but I can't determine what is supposed to complete startup ... anyway if U can assist thanks ! 
![image](https://user-images.githubusercontent.com/31119577/137641168-e667f135-d94c-46d5-addc-4b1cf62e439e.png)

**Comment by richardpack** [comment]
Not really sure given the description, but since you say the system is very
large, it's worth pointing out that homekit only supports 150 devices per
bridge. So if you have more than 150 devices, try to split the devices up
across multiple bridges. You can specify which VIDs to load on each bridge
in the configuration. I'd start by trying a single bridge with a single VID
and see if that works. If so, then that is the issue.

**Comment by stevefnz** [comment]
Hi richard

Thanks for the reply

Yep Im aware of the 149 issue so I set up a white list of only 4 vids …. I presume it doesn’t try to create anything expect those … I have been using Homeassistant and the method did work in that system in python

Does the message “parsed xml successful ‘ mean it did get to the end of processing the xml file to it should have returned to HB and continued to start ? I presume once it gets to end of the config data from vantage it should return to HB

I do see all the comms data continuing to come from vantage in debug so its talking fine

….. hmmmm … ok maybe i try one vid …. Ah one question ! , does it support “TASK” type vids as well as “LOAD” etc  ? as that’s what a lot of mine are….. program tasks for scenes etc in vantage ….

Thanks

Stephen

**Comment by richardpack** [comment]
Good point, it only currently supports switch, outlet, fan and dimmer (But
dimmer has a bug I haven't been able to fix yet so its disabled in the
latest version). If you want to add task, you can do that by updating
homebrfidge-vantage-static.js#225, I'd be happy to merge that change in.

**Comment by stevefnz** [comment]
Yep I’ll have a look , I don’t know typescript but I’ll figure it out or send U what I think

What’s the bug ? I have done a lot of vantage driver programming

Thanks 🙏

Regards Stephen F


On 19/10/2021, at 09:11, richardpack ***@***.***> wrote:

﻿

Good point, it only currently supports switch, outlet, fan and dimmer (But
dimmer has a bug I haven't been able to fix yet so its disabled in the
latest version). If you want to add task, you can do that by updating
homebrfidge-vantage-static.js#225, I'd be happy to merge that change in.

**Comment by richardpack** [comment]
Thanks, if I get around to it soon I can try too. Do you know the
controller command(s) for type TASK? If you know what the task command
looks like, adding support for it isn't that big of a deal.

The bug is dimming functionality only works once, meaning you can only dim
one light and then all dimmers don't work. So there is some state
management issue (I think) in the plugin but its hard to debug. If I send
the same commands directly to the controller, everything works fine.

**Comment by stevefnz** [comment]
Hi Richard

Yep I tried with a single VID but it still never loads and hangs in a loop on starting so Home Bridge never starts

Unf im struggling with how to debug in HB as I need to sit down and probably learn the process of plugins / build compile etc , I did code full time 30 years ago , in the old languages haha COBOL FORTRAN , so I get myself around just ok with the new stuff 😊 logic is fine just never really learnt Object Orientated , but I did write my own device drivers for the vantage stuff that didn’t exist ……..

Anyway ill keep looking , typescript / JS is also new to me  so im in deep haha 😊

I have attached the list of vantage host commands , I presume you have these anyway , TASK is usually executed with a PRESS

I did get Home Assistant working with my vantage but I am keen to try homebridge as it links better to alexa / siri / homekit , but anyway ill keep looking , maybe I need to try a smaller system , my Vantage has over 11k vids and some uncommon interfaces so maybe its throwing your interface , I did do a bit with the guy who wrote the home assistant version which is in python which was a bit easier for me to debug , that code is here https://github.com/gjbadros/hass-vantage if its any value even for your dimmer problem , I guess you can do python if you do Jscript 😊 😊

Oh I could also send you my large vantage .dc file if you wanted a large file for testing

Anyway ill report any stuff I find

Regards



Stephen Farmer

Mobile +64-21-227-5079
Email ***@***.******@***.***>
[Description: Downforce med]<http://www.downforce.co.nz/>
30 Angle Street, Onehunga, Auckland, 1061, New Zealand <  PO Box 42153, Orakei, Auckland 1745  <  www.downforce.co.nz<http://www.downforce.co.nz/>
